### ISSUE TITLE
Users state does not change after logoff

### ISSUE THREAD

**Issue by gpadbidri** [jcbrand/converse.js#327]
I want the conversejs code to reflect the "OFFLINE" icon besides the user, as soon as any user instantly logs off or closes the browser instance.. Currently, it happens but after some delay. Following is the Test Case :

For Example : 
1.	“Gauri” logs in to ConverseJS Web Client on one machine.
2.	“TestUser” logs in to ConverseJS Web Client on other machine.
3.	 “TestUser” logs off / closes the browser window.
4.	Notice : “Gauri” still sees the “TestUser” as online
5.	Expected : “Gauri” should instantly see the user as OFFLINE.

Seems like the RosterContactView -> render() is invoked after some time. I also know I need to customize the code. Where can I tweak the code to get this thing working. Can you guide me through this one ?

**Comment by nodiscc** [comment]
Just a guess, but isn't this due to the fact that your BOSH server doesn't know about "TestUser" logging off in the first place, because you closed the browser window and killed ConverseJS without sending a notification to the BOSH server?

If I remember correctly the BOSH server probes the clients regularly to see if they're still alive, so you have to wait the next probe for the server to notice TestUser is offline. This is what I also experience with Prosody's XMPP server BOSH component.

I may  be wrong.

**Comment by jcbrand** [comment]
What you want to do is add an event handler for when the window or tab is being closed and then set the user's xmpp status to "offline". I'm however not aware of such an event which works reliably.

It would be something like the event listener for ``beforeunload`` but that particular event won't work because it also gets called when the page is reloaded.

In the event handler you want to call something like: ``converse.xmppstatus.setStatus("offline")``

A pull request which does this would be welcome.

**Comment by gpadbidri** [comment]
Thanks for your response...I am currently working on reliably captuing the Browser Tab Close event. However, the above single line of code did not work for me, meaning the OFFLINE status was NOT instantly reflected to other users. However when I add the following lines of code, it seems to reflect instantly : 

this.clearSession();
converse.xmppstatus.setStatus("offline"); 
converse.connection.disconnect();

I think Disconnect() did the magic. Is it safe to call it the way I mentioned ?  Kindly let me know your views. Thanks !

P.S : Once I have the Browser Tab Event handled gracefully, I will Push the code.

**Comment by jcbrand** [comment]
hi @gpadbidri, looks good, calling ``converse.connection.disconnect();`` makes sense.

**Comment by jcbrand** [comment]
@gpadbidri How's it going with that pull request? :)
