### ISSUE TITLE
Single session in converse.js

### ISSUE THREAD

**Issue by vnod-ideas2it** [jcbrand/converse.js#334]
Actually, I am using converse.js with prebind options in tigase. Converse js Create a single session when I login thats fine. The problem is when internet connection is gone or or tab closed after certain time XMPP session (BOSH)  has been closed. So I cannot do more without re-login, because Invalid SID error. Is there any way to handle this problem.

**Comment by jcbrand** [comment]
If you get an invalid SID error then it's likely that the BOSH connection has been closed. This is probably what's happening in your case. You can't close the tab and expect to later attach to that session again.
That's simply the way it is.

If you want completely smooth integration without any logging in, then you need a backend web app which does prebind for you. See the **prebind_url** configuration setting in the documentation.

I'm closing this ticket because it's neither a feature or a bug. For further support please write to the mailing list: conversejs@librelist.com
