### ISSUE TITLE
Refreshing the Page with a ChatRoom open causes the Participant List to vanish 

### ISSUE THREAD

**Issue by gpadbidri** [jcbrand/converse.js#335]
Following is the test Case : 

1. Launch a Chat Room with Participants P1, P2, P3 and P4
2. Keeping the ChatRoom window open, try to refresh the browser window.
3. OBSERVE : The participant list will display only the LOGGED IN users name.
Expected Result : The ChatRoom must list ALL participants consistently...

What should I do to resolve this issue ?

**Comment by jcbrand** [comment]
Which version are you using? This should be fixed in 0.9.0.

**Comment by gpadbidri** [comment]
Can you point me to the COMMIT that contains changes specific to this issue, that way it gets easier for me to merge ? I am using 0.8.6...I have made a lot of changes to the existing file...Hence, the request !

**Comment by jcbrand** [comment]
It wasn't a single commit. I did a large refactoring so that strophe.muc.js could be completely removed.
Work was done in this branch: https://github.com/jcbrand/converse.js/tree/muc_refactoring
You can try to merge that branch and see if everything still works but there's no guarantee.

It's a bad idea to modify converse.js itself. Generic reusable changes you make should be merge back to converse.js itself through pull request and project-specific code should go into plugins. Now you're stuck with an older version and are not able to upgrade.
