### ISSUE TITLE
listen.on('messageSend',msg) does not seem to return an object with documented get properties

### ISSUE THREAD

**Issue by metalaureate** [jcbrand/converse.js#336]
I (somewhat urgently if I may throw myself on your mercy) need to be able to reference the message text and the recipient ID.

According to the documentation

```
converse.listen.on('messageSend', function (msg) {
    $log.info(msg);
});
```

this is meant to return a backbone object with get properties including `.get('message')`.

But `.get('message')` returns undefined. What am I doing wrong?

**Comment by metalaureate** [comment]
@jcbrand this what is returned : http://screencast.com/t/MYVYp0ZGNTu

I've checked every method and property and can identify no reference to the recipient.

**Comment by jcbrand** [comment]
@metalaureate ``jquery.trigger`` which fires the event inserts an event object as first argument to the callback.

So that's the object you were seeing all the time. The message is therefore the 2nd argument. Looking at the code again, I see that the message is simply the text message and not the Backbone object, sorry for mistaking that.

Protip, in the future you can see which arguments are passed to a function by simply inspecting the ``arguments`` variable. This would have shown you that there were more arguments passed to your handler and that the second argument is what you wanted.

**Comment by metalaureate** [comment]
Thanks @jcbrand for the tip. The message alone is not very useful if it you don't also know who sent it. :)

This whole experience prompted me to modify a Prosody mod to do it the right way, XMPP server-side, in Lua. It took less time than to complain about Backbone. :) 

If you have a moment, I could use some pointers for how modify converse.js to allow programmatic opening of chat rooms, as described in my post to the list recently. I can see a lot more custom converse.js development in my future...

**Comment by jcbrand** [comment]
*messageSend* is always pertaining to the current user. If you don't know who the current user is, you can do ``converse.tokens.get('jid')``.

**Comment by metalaureate** [comment]
Sweet. Thank you.
