### ISSUE TITLE
Fetch Chat Room Configurations based on JID

### ISSUE THREAD

**Issue by gpadbidri** [jcbrand/converse.js#346]
I was able to SET the ChatRoom configurations via SendConfigurtion(). Hwever, what is the API to fetch the ChatRoom Configurations based on a JID ? Also, how and from where can I invoke the updateRoomsList() API when any user joins the Chat Room ? I want the Contacts Panel to update the Chat Rooms !

**Comment by jcbrand** [comment]
@gpadbidri Like I've already mentioned before. Questions such as this should go to the mailing list and not the issue tracker because they are neither bugs nor feature requests.

In any case, look at the **configureChatRoom** method. Converse.js sends an IQ stanza to the server to ask it for the room's configuration. There is no public API for this.
