### ISSUE TITLE
API consistency & muc : chats.get() vs. chats.open()

### ISSUE THREAD

**Issue by pzia** [jcbrand/converse.js#355]
Current API chats.get() provide both one-to-one and muc chats.
But chats.open() will only allow to open one-to-one chats.

In other words : 
- either chats.open() should work with muc talks
- or there is a need for a specific API for muc ?

I can try to make a patch, but I'd prefer have some guidance about the "way to go".

**Comment by jcbrand** [comment]
I'm a bit unsure whether it's a good idea to use the ``chats`` namespace for both SUC and MUC.

I think it'll probably be simpler and easier if we introduced the ``rooms`` namespace for MUC.
So opening a room would then be done with ``converse.rooms.open``.

The code should be very similar. Chat rooms are also ``ChatBox`` models, they just have different views (``ChatRoomView`` instead of ``ChatBoxView``). That's really the main difference.

**Comment by jcbrand** [comment]
To get an idea what code should go in ``converse.rooms.open``, you can take a look at the ``createChatRoom`` method of the ``RoomsPanel`` view.
