### ISSUE TITLE
bower install converse fails

### ISSUE THREAD

**Issue by scags9876** [jcbrand/converse.js#379]
When I try to install converse.js via bower, I get the error below, indicating that the version of crypto-js specified as a dependency does not exist:

> bower install converse.js
...
bower crypto-js-evanvosberg#3.1.2-5                          ENORESTARGET No tag found that was able to satisfy 3.1.2-5

Additional error details:
Available versions: 3.1.4, 3.1.3

**Comment by jcbrand** [comment]
Yes, an older release of crypto-js is no longer available via bower. I think it's because @evanvosberg changed the naming convention of tags/releases. Older releases where prefixed with "release-" and newer releases aren't. See here: https://github.com/evanvosberg/crypto-js/releases

Would be best if bower could be a bit more clever here and also pick up older releases, it might be worth making a bug report on the bower page.

I've already updated bower.json in the master branch of converse.js but this won't fix the problem for older releases of converse.js. I'll make a new release of converse.js soon, and from that version onwards at least this problem should be fixed.

**Comment by scags9876** [comment]
Great! Thanks!

**Comment by evanvosberg** [comment]
Just to make it more understandable, all version prior 3.1.3 are not designed to use with bower.

Why?
- all prior versions don't have a `bower.json` file
- `bower` doesn't prefer pre-release versions like `npm`
 - npm: want `3.1.2` get 3.1.2-5
 - bower: want `3.1.2` get `3.1.2`

For those reasons I renamed all prior versions to make them not available as `semver` tags, the releases before are totally different and could confuse people.

So `3.1.3` is the first released design to use with `bower` and `npm`, the current stable version is `3.1.4` and `3.1.5` with small fixed is in dev ...

**Comment by jcbrand** [comment]
@evanvosberg, thanks for responding.

It's unfortunate that you renamed those releases because now previous tags/releases of converse.js (and I assume other projects as well) cannot be built any more.

I can fix this in the master branch of converse.js, but older tags are supposed to be immutable so it can't easily be fixed there.

We've been using crypto-js via bower for quite a long time now and the fact that those previous releases weren't consciously designed to work with bower didn't pose a problem to us at all.

In the Python community, it's taken for granted that old releases are never changed or removed from Pypi (the package store). I wish the same could be expected from Javascript/bower.

**Comment by jcbrand** [comment]
To anyone who reads this ticket and is looking for a workaround, you need to edit ``bower.json`` and give the following value for ***crypto-js-evanvosberg***:

```
"crypto-js-evanvosberg": "https://github.com/evanvosberg/crypto-js.git#release-3.1.2-5",
```
