### ISSUE TITLE
mam preloaded messages and offline messages issue working together 

### ISSUE THREAD

**Issue by teseo** [jcbrand/converse.js#411]
Hello JcBrand,

We finally decided to implement the functionality  [following your recommendation](https://github.com/jcbrand/converse.js/issues/230) and  converse events, when chatBoxOpened, I capture the event, I send the iq stanza to retreive the messages with a limit of 10.

What I am doing is fetching the messages and I insert them in the BrowserStorage same way converse naturally do it and then let converse fetch the stored messages and display it. That's all fine.

My only missing piece is when there's an offline message, it gets displayed before the message event is triggered. 

Ideally it would be great if, in conjunction with mam preloaded, we can display the offline messages after all the messages are displayed.

What would be your suggest to accomplish this?

Many thanks!

**Comment by jcbrand** [comment]
Hi @teseo 

The issue tracker is only for bug reports or feature requests. I provide some limited free support on the mailing list, and there might also be other people willing to help you there: conversejs@librelist.com
Otherwise you can ask me about my consulting rates [here](https://opkode.com/contact.html)

In this particular case, I don't know enough about your particular setup or the problem itself to have a suggestion. It would require me to do some research first.
