### ISSUE TITLE
make: ./.bundle/bin/sass: No such file or directory

### ISSUE THREAD

**Issue by joe-liquid** [jcbrand/converse.js#417]
Hi, 

I am trying to theme Converse following the instructions on https://conversejs.org/docs/html/theming.html. I have ran make serve successfully but am unable to rum make css. I get the following error returned from console when I do so. Do you know what the issue is here? 

./.bundle/bin/sass -I .bundle/bin sass/converse.scss css/converse.css
make: ./.bundle/bin/sass: No such file or directory
make: *** [css] Error 1

**Comment by joe-liquid** [comment]
I am on OSX 10.9.5. Path to Ruby and SASS is /usr/bin/sass, /usr/bin/ruby.

**Comment by joe-liquid** [comment]
Gem version is 2.4.1.

**Comment by joe-liquid** [comment]
By running make dev in console I have resolved the issue with the .bundle directory. I am now having this issue with bourbon. 

sass/converse.scss css/converse.css
Error: File to import not found or unreadable: ../ruby/1.9.1/gems/bourbon-4.2.1/app/assets/stylesheets/_bourbon.
       Load path: /Users/joe/Desktop/converse.js/.bundle/bin

**Comment by joe-liquid** [comment]
I believe this is failing because of the path to .bundle/bin. Do I need to add this?

**Comment by joe-liquid** [comment]
What do I need to add to PATH to load the bundler installed gems within the converse directory after the environment is set up?

**Comment by jcbrand** [comment]
Are you using a master checkout or a release of converse.js?

The Makefile installs the ruby dependencies in the `.bundle` directory. This should happen when you run `make dev`. Bourbon should also be installed there.

You can also do this manually. If you have bundler installed globally:

```
    gem install --user bundler --bindir .bundle/bin
    ./.bundle/bin/bundle install --path .bundle --binstubs .bundle/bin
```

Then check whether you can find bourbon in `.bundle/ruby/1.9.1/gems/``.

Otherwise, show me exactly what you have in the `.bundle` directory.

**Comment by joe-liquid** [comment]
I clone converse then run make dev in console. 

Inside the .bundle directory are bin, config, ruby directories. Within ruby dir is 2.0.0 dir. Within gems dir are bourbon-4.2.3, sass-3.4.14, thor-0.19.1. 

In converse.scss you are trying to load @import "../ruby/1.9.1/gems/bourbon-4.2.1/app/assets/stylesheets/_bourbon";

This looks like a version issue to me at the moment. I also get the following error so I need to address this also I believe once the issue with the versions is addressed. Can you recreate the issue?

WARNING:  You don't have /Users/joe/Desktop/converse.js/.bundle/bin in your PATH, gem executables will not run.

**Comment by jcbrand** [comment]
I think we need a Gemfile.lock which locks the versions. The the problem should go away.

I quickly committed my Gemfile.lock, but it doesn't specify the Ruby version yet, so it probably won't yet solve the problem for you.

https://github.com/jcbrand/converse.js/commit/b366bf309b53b37a283adc979a4e2290eed3585c

BTW, you can safely ignore that warning if you use the Makefile because it uses the path to executables.

**Comment by joe-liquid** [comment]
I cloned and ran make dev as still see the same problem as I pointed out before. Ruby version is on 2.0.0 and the bourbon include is failing in the converse.scss file. Is there any quick fix for this to start theming before you can look into this issue further. Really keen to see what theming I can do now you have separated everything nicely in this latest release.

**Comment by jcbrand** [comment]
There are a few things you can try as workarounds. For one, change the path to bourbon in `sass/converse.scss`. Alternatively, pin the Ruby version in Gemfile.lock.
