### ISSUE TITLE
Users appear in Pending List after Accepting Friend Request when other user is OFFLINE.

### ISSUE THREAD

**Issue by gpadbidri** [jcbrand/converse.js#474]
Hi JC,

I have found a BUG in your code where the test case is as follows :

1. User A sends User B a Friend Request.
2. User A now goes Logs Out.
3. User B logs In and Accepts User A's Friend Request.
4. User A's name disappears from Pending List but is ALSO not present / added to Friends List.
5. Now User B Logs in and has User A in his Friends List. Also, now User A sees User B in Friend List.
<b>OBSERVE : </b> From Point no. 5, we can say that unless User B comes Online, User A will NOT be User B's Friend and will not appear in User A's Friend List.

NOTE : Same is the case with the <b>auto_subscribe:true</b> configuration,does not work as expected when other user id OFFLINE.

<b>Considering Facebook as a Model, when we accept a friend request, that person becomes our Friend regardless of his OR her Online / Offline Status.</b> 

What can be done to resolve this Friend Request Acceptance issue while other user is OFFLINE ? Any pointers could be of help.
 
Best Regards,
Gauri Padbidri

**Comment by jcbrand** [comment]
> User A's name disappears from Pending List but is ALSO not present / added to Friends List.

Don't you mean User A's name disappears from the **Requesting contacts** list?

Here's how it should go:

1. User A sends User B a Friend Request.
2. User A now goes Logs Out.
3. User B logs in
4. User A must now appeared under  **Requesting contacts** in User B's roster.
5. User B accepts User A's friend request.
6. User A must now appear under **Pending contacts** in User B's roster.

This will be so until User A logs in, which is when User A's chat client (converse.js) will automatically reciprocate the friend request which was accepted by User B.

So the next two steps are:

7. User A logs in.
8. Now User A will appear as a normal contact in User B's roster.

> when we accept a friend request, that person becomes our Friend regardless of hi / her Online / Offline Status. What can be done to resolve this Friend Request Acceptance issue while other user is OFFLINE?

This is not the way XMPP works. XMPP is more like twitter than Facebook.
In XMPP, one user can "follow" another user, without that user following back.

So that have bidirectional "friendships" like in Facebook, both users must "friend" one another, so both users must initiate a "friend request".

Converse.js simplifies this a bit by automatically making a friend request back when you accept a friend request, so you don't have to do it manually.

But the point is therefore that both user's clients need to accept a friend request, not just one client, which is why User A needs to log in first again (so that her converse.js can accept the friend request from User B).

There's no way around this that I can think of currently.

**Comment by gpadbidri** [comment]
@jcbrand : Exactly, That is how it is working now. Meaning,users will NOT appear in each others Friend List unless both are online after accepting the Friend Request. 

But my question is, can we NOT do something OR is there no way OR can  you not propose a solution that we have the user in our Roster immediately after Accepting the Request regardless of his Online / Offline status ?

**Comment by jcbrand** [comment]
> But my question is, can we NOT do something OR is there no way that we have the user in our Roster immediately after Accepting the Request regardless of his Online / Offline status ?

Reading this question makes it seem to me like you didn't read or understand the long explanation I gave above as to why it behaves the way it does currently and where I mention that I'm not aware of a way to change it to how you want it to behave. At least not in converse.js.

You could perhaps develop a module for Prosody which automatically reciprocates friend requests when they are accepted.

**Comment by gpadbidri** [comment]
@jcbrand : Thanks for your comment. I did read your entire explanation, but could NOT make sense of what you meant when you said <i>"There's no way around this that I can think of currently."</i> (As i thought may be later) Hence the confusion. However, now it is clear of what you mean. Thanks for the Prosody Module solution. :)

**Comment by jcbrand** [comment]
You're welcome @gpadbidri :)
