### ISSUE TITLE
ConverseJS integration

### ISSUE THREAD

**Issue by BenJaziaSadok** [jcbrand/converse.js#498]
I have a working Openfire server and i want to integrate converseJS for my users and olso for guests for multi-user chat.
The guess part is working well with anonymous aithentification.
When is set the code for registred users, i get users connected but in the Client Sessions i get the Resource value null so that messages are unreachable.
Here is the script:
require(['converse'], function (converse) {
    converse.initialize({
        bosh_service_url: 'http://chat.server.com:7070/http-bind/', 
        i18n: locales.en, 
        show_controlbox_by_default: false,
        allow_muc:false,
        allow_contact_requests:false,
        authentication: 'login',
        keepalive: true, 
        allow_registration:false,
            auto_login: true,
            jid: '<?php echo ($_SESSION['PK_USER']) ?>'+'@chat.server.com/',
            password: '<?php echo($_SESSION['S_PASS']) ?>',
            auto_list_rooms: true
    });
});

**Comment by jcbrand** [comment]
I already helped you in the discuss chat room.

**Comment by BenJaziaSadok** [comment]
i saw nothing, could you post it here?

**Comment by jcbrand** [comment]
02:45 kassav:  here is the connexion script
02:45 kassav:  require(['converse'], function (converse) { converse.initialize({ bosh_service_url: 'http://chat.server.com:7070/http-bind/', i18n: locales.en, show_controlbox_by_default: false, allow_muc:false, allow_contact_requests:false, authentication: 'login', keepalive: true, allow_registration:false, auto_login: true, jid: '<?php echo ($_SESSION['PK_USER']) ?>'+'@chat.server.com/', password: '<?php echo($_SESSION['S_PASS']) ?>', auto_list_rooms: true }); });
02:45 kassav:  did i miss something?
02:46 me:  The problem is probably with the jid value that you are passing in
02:46 me:  yes
02:46 me:  the "/" at the end of the jid value
02:46 me:  is probably interpreted as a null resource
02:47 kassav:  i want to note that anonymous connexion is working well
02:48 me:  just remove the "/" at the end of the jid that you pass into converse.initialize
02:48 me:  then it'll work I think

**Comment by BenJaziaSadok** [comment]
not solved, same issue
