### ISSUE TITLE
Converse not sending status after disconnect

### ISSUE THREAD

**Issue by lbischof** [jcbrand/converse.js#521]
If Converse gets disconnected from the bosh server (prosody restart etc) then I get sent to the login panel. After logging in Converse doesn't send the status so everyone else thinks that persion is offline. Did I configure something wrong?

Edit: if I "change" (it is already available) status then it sends the presence.

**Comment by lbischof** [comment]
It seems when I login again it doesn't correctly renew the bosh connection, because if I reload the page and login again the original bosh connection times out.

**Comment by lbischof** [comment]
Is there anyway to disable sessionstorage? I think that's the problem and it doesn't seem to be necessary performance wise (I only have about 70 users)

**Comment by jcbrand** [comment]
> After logging in Converse doesn't send the status so everyone else thinks that persion is offline.

Sounds like a bug. It probably doesn't send it again because it knows that it's done it already before and isn't aware that the session was interrupted.

> Is there anyway to disable sessionstorage?

I wouldn't go down that route. sessionStorage is baked into the cake by now and has many advantages. For example, you don't want to fetch the whole roster every single time someone reloads the page for example.

**Comment by lbischof** [comment]
Should converse log the user out if I reload or exit the page? For me it doesn't and just times out after 60 seconds (bosh timout of prosody). If I clear the sessionstorage everytime someone visits the page then it works (everything except logout, but if I reconnect within the 60 seconds it keeps working)

**Comment by jcbrand** [comment]
No, one of the points of using sessionStorage is to maintain the session across page loads (if you use the `keepalive` option). This works very well and many people rely on this functionality.

Are you using the 'keepalive' option?

**Comment by lbischof** [comment]
I think keepalive is true by default. Here is my config:
```
   converse.initialize({                                                                                                                                                                      
            bosh_service_url: 'https://prosody.domain.com:5281/http-bind/', 
            i18n: locales.en,                        
            show_controlbox_by_default: true,                                                                                                                                                  
            hide_muc_server: true,                                                                                                                                                             
            roster_groups: false,                                                                                                                                                              
            allow_contact_removal: false,                                                                                                                                                      
            allow_contact_requests: false,                                                                                                                                                     
            allow_registration: false,                                                                                                                                                         
            hide_offline_users: true,                                                                                                                                                          
            auto_list_rooms: true,                                                                                                                                                             
            debug: true                                                                                                                                                                        
    });             
```

**Comment by irek-zaripov** [comment]
As I see keepalive is false by default("converse.js" line 318 of 6674). But after function converse.initialize, the status is not sent to XMPP server even with keepalive:true authentication:true.

**Comment by irek-zaripov** [comment]
Sorry, keepalive:true authentication:prebind

**Comment by irek-zaripov** [comment]
I can confirm, that with clean sessionStorage the status 'online' is sent to the XMPP server. If the status is taken from the Session Storage, it is not sent to the XMPP server.

**Comment by irek-zaripov** [comment]
But when 'auto_away' event is occurred the status is sent to the XMPP server.

**Comment by irek-zaripov** [comment]
So I can suggest a workaround by setting 'auto_away' => 5 for example.

**Comment by lbischof** [comment]
Any update on this? Using auto_away is only a workaround and shouldn't be needed. This is a major issue for me since users that login with conversejs aren't seen by other users.

**Comment by jcbrand** [comment]
@lbischof I think this issue is related to #536 (it's the same bug).

The solution is to add better logic when deciding whether a new presence stanza should be sent out or not.

Here is where that presence is sent out (depending on `initial_presence_sent`).
https://github.com/jcbrand/converse.js/blob/master/converse.js#L4529

The fix here is to determine whether there was a disconnection just before. Another useful check could be to send out the presence when the JID's resource has changed.

**Comment by jcbrand** [comment]
@lbischof Should be fixed now, see the referenced commit above. Can you please give it a test to confirm whether the issue is solved for you?

**Comment by lbischof** [comment]
Thanks! I'll test it and report back asap

**Comment by irek-zaripov** [comment]
As for my tests with roundcube plugin, the bug is not fixed. Because of the condition https://github.com/jcbrand/converse.js/blob/master/converse.js#L4949 
                                } else if (converse.connection._proto instanceof Strophe.Websocket ||
                                           !converse.keepalive ||
                                           !converse.initial_presence_sent
                                        ) {
                                    /* We're not going to fetch the roster again (because we have
                                     * it already cached in sessionStorage, but we still need to
                                     * send out our presence because this is a new session.
                                     * See: https://github.com/jcbrand/converse.js/issues/536
                                     */
dose not work in the roundcube plugin. We have to use keepalive in this plugin don't use Websocket. 
What's wrong can happen if we will send presence anywhere? As I understand this function is for fetching roster, and after fetching from sessionStorage the presence should be send anywhere in case of use as roundcube plugin.

**Comment by jcbrand** [comment]
>What's wrong can happen if we will send presence anywhere?

@irek-zaripov The point is to avoid unnecessary requests and network traffic. 

> We have to use keepalive in this plugin don't use Websocket. 

If you use `keepalive`, then it shouldn't be necessary to send the presence stanza whenever the page gets reloaded, because converse.js reattaches to the same session. So if it's still now working in the roundcube plugin, then it sounds to me like the roundcube plugin is doing something wrong like establishing a new BOSH session every time the page gets loaded (thereby making the keepalive setting useless). If that's the case, then the problem is in the roundcube plugin and how it works and not with converse.js.

Also, just to clarify. Although it's recommended, you're not forced to use `keepalive` when using BOSH and it's definitely possible to set `keepalive: true` but still have things configured and set up is such a way that the keepalive functionality isn't actually being used. That would then be a misconfiguration.

**Comment by jcbrand** [comment]
Looking at the code again, it doesn't look like you actually tested anything @irek-zaripov, because the way the code is currently, a presence stanza will be sent out every time the page loads (an unintended bug on my part) due to the fact that `initial_presence_sent` doesn't keep it's value across page loads.

**Comment by irek-zaripov** [comment]
@jcbrand I have tested by cloning directly from master branch:
# git clone https://github.com/jcbrand/converse.js
Thank you for clarifying the keepalive option. I agree that it is roundcube plugin's issue. 
With keepalive: false the presence status is send, thanks!

**Comment by irek-zaripov** [comment]
Just for information. As roundcube plugin have to initialize a new BOSH session for any new roncube's rendered web page, and converse.js have a performance issue when fetching > 1000 contacts(regardless from sessionStorage or XMPP server) the converse.js as roundcube plugin can be used only in small installations(may be < 100 users).

**Comment by jcbrand** [comment]
@irek-zaripov I've now simplified and improved the code a bit more. Now, even if converse.js is misconfigured so that `keepalive` is `true`, but the session wasn't actually restored and instead a new session has been established, the presence stanza will still be sent out.

Could you please set `keepalive: true` and then test with the new code to see if it now works for you?

Thanks!

**Comment by jcbrand** [comment]
@irek-zaripov One trick you can use to improve performance for large rosters is to set `show_only_online_users: true`.

**Comment by irek-zaripov** [comment]
OK @jcbrand I'have compiled, with (keepalive: true) it can't initialize now.
GET https://bosh.url.xxx:7443/http-bind/ 400 (Bad Request)
send @ converse.min.js?s=1452837647:237
p.extend.ajax @ converse.min.js?s=1452837647:237
startNewBOSHSession @ converse.min.js?s=1452837647:237
attemptPreboundSession @ converse.min.js?s=1452837647:237
initConnection @ converse.min.js?s=1452837647:237
_initialize @ converse.min.js?s=1452837647:237
d.initialize @ converse.min.js?s=1452837647:237
b.initialize @ converse.min.js?s=1452837647:237
rcmail_converse_init @ converse-rcmail.js?s=1451536957:16
(anonymous function) @ ?_task=mail&_mbox=INBOX:410
t @ converse.min.js?s=1452837647:237
(anonymous function) @ converse.min.js?s=1452837647:237

As for (show_only_online_users: true) it can't help to my mind. because of offline users are fetched anywhere.

**Comment by irek-zaripov** [comment]
With 'keepalive: false' it works fine

**Comment by irek-zaripov** [comment]
I have tested with option (show_only_online_users: true) it takes the same time. Because of when roundecube renders a new page (opens a e-mail for example) it initializes a new BOSH session, and it takes a very long time when there are so many users in the roster contact.
