### ISSUE TITLE
Set the full name for a roster contact

### ISSUE THREAD

**Issue by YoMismo4** [jcbrand/converse.js#541]
I want that the roster contacts instead of showing their usename or jid, it could show only the name of the contact.

**Comment by jcbrand** [comment]
If the user has a VCard entry with their full name, then that will be shown. Otherwise the JID is shown. So one solution is to make sure all users have valid vCards.

One thing we can do in Converse.js is to add the ability to set a full name on roster contacts.

I'll leave this ticket open for that enhancement.

**Comment by YoMismo4** [comment]
I'am using openfire and VCard table doesn't have any registers, it's that a problem?

**Comment by jcbrand** [comment]
It means there aren't any full names to show (at least not in VCards).

**Comment by YoMismo4** [comment]
Where do full name comes from?

**Comment by jcbrand** [comment]
> Where do full name comes from?

Either from VCards or from the `name` attribute in the roster entry of a user. Neither can be set in converse.js, but it will read and use them if they're available.

See here concerning `name` attr in roster: https://xmpp.org/rfcs/rfc6121.html#roster-syntax-items-name

**Comment by YoMismo4** [comment]
ok, thanks
