### ISSUE TITLE
Offline chat status prebind problems

### ISSUE THREAD

**Issue by mustafaevcil** [jcbrand/converse.js#547]
My users login system and chat starts automatically with prebind. Each user have only one bosh session in browser tab. When user open new tab, another bosh session is created for active user. My first problem is that chat status change to offline, other tabs not updated to offline status but other status (online,busy..) are working successfully. Offline status isolates the session in browser tab and not receive message and changing roster status. In the same way, changing status to offline for other chat users doesn't propagate to their rosters.

**Comment by jcbrand** [comment]
Please make a separate issue for each problem, we don't handle multiple problems per issue.

Your second problem appears to be related to OpenFire and not something in converse.js.

**Comment by jcbrand** [comment]
After spending time investigating and working on this issue, I've come to the conclusion that `offline` should be removed from the dropdown where the user chooses a chat state.

The reason for this is that according to the XMPP spec, `offline` is not a state in the same sense as the other states (`online`, `busy`, `away`).

See here: https://xmpp.org/rfcs/rfc6121.html#presence-syntax-children-show

There is really no `offline` state, there is only `unavailable`, but that is a presence type and not a chat state and the logic for it is different.

When a chat session goes "offline" (i.e. a presence with type `unavailable` is sent out), then it cannot be taken out of that state by receiving presence stanzas from other connected clients (from the same user). This means, if the user chooses "offline", and all other tabs with converse.js also go "offline", then when the user later chooses "online" again, the other tabs can't automatically become online again as well, because they're all in the `unavailable` state.

Additionally, the `log out` option is basically the same as the `offline` state. Both send out a presence with type `unavailable`, the only difference is how they're presented in the UI of converse.js.

I'll probably add a config option to allow people to use the `offline` state as it currently exists (together with some new code which propagates the state to other connected converse.js clients) but it'll be disabled by default and it will have this problem described above where clients (e.g. other tabs) cannot be taken out of the offline/unavailable state when in one tab the state is changed back to something else.

**Comment by irek-zaripov** [comment]
` I'll probably add a config option to allow people to use the offline state as it currently exists (together with some new code which propagates the state to other connected converse.js clients) but it'll be disabled by default and it will have this problem described above where clients (e.g. other tabs) cannot be taken out of the offline/unavailable state when in one tab the state is changed back to something else.`
 @jcbrand may be will be better to change the status `offline` to `invisible` ?(http://xmpp.org/extensions/xep-0018.html)

**Comment by irek-zaripov** [comment]
XEP-001 is rejected, but XEP-0126 is not http://xmpp.org/extensions/xep-0126.html

**Comment by jcbrand** [comment]
@irek-zaripov: From the doc: `WARNING: This document has been Rejected by the XMPP Council. Implementation of the protocol described herein is not recommended under any circumstances.`

There is a newer XEP which specifies a way to implement the invisible state, but it suffers from the same problem in converse.js. The state will not propagate across tabs because the "invisible" state is not broadcasted, it's only communicated to the server, not to other connected clients (from the same user).

http://xmpp.org/extensions/xep-0186.html

**Comment by jcbrand** [comment]
XEP-0126 might work, but it's quite complicated and I'm not going to implement it in the context of this issue.

**Comment by irek-zaripov** [comment]
OK, by openfire it is not supported too...
