### ISSUE TITLE
Prebind idle session handle problem

### ISSUE THREAD

**Issue by mustafaevcil** [jcbrand/converse.js#561]
My web application uses prebind for single session. If the user closes browser tab, the session remains  online and user's contact sees still this user as online. I tried to solve this problem with xmpp server. I use openfire and ejabberd server with idle connection policy (sends ping in interval) for problem. The converse sends response (ping ack) perfectly but session is terminated suddenly. I set timeout for response, but problem didn't solved. Actually, I want to solve this problem in client. I catch close event with beforeunload but I didn't distinguished redirect in page and close action. If I close this session with converse.disconnected() method, it will be very nice. How can I solve this problem in client ? Could conversejs provide any listener for this?

**Comment by jcbrand** [comment]
>  If the user closes browser tab, the session remains online and user's contact sees still this user as online.

For a while, but then the XMPP server should eventually set the user's status to unavailable (due to inactivity).

>  I catch close event with beforeunload but I didn't distinguished redirect in page and close action

yes, that's the problem with that event. You don't know if the tab is closed or if the user navigated to a different page in the same site.

> Could conversejs provide any listener for this?

There's no event that will tell you when the tab was closed (and only that) as far as I'm aware.
