### ISSUE TITLE
Unread message counter is reset when the chatbox is closed

### ISSUE THREAD

**Issue by rlanvin** [jcbrand/converse.js#591]
When a chatbox is closed, and then re-opened upon reception of a new message, the notification (visible in the browser tab's title) will show "Messages (XX)", with XX = total number of messages in the conversation, instead of "Messages (1)" as expected.

To reproduce:
1. Start chatting with another user
2. Close the chatbox completely
3. Have the other user send you a message
4. The chatbox re-opens automatically, and the browser tab's title will show the total number of messages

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30842993-unread-message-counter-is-reset-when-the-chatbox-is-closed?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by novokrest** [comment]
@jcbrand Can I work on this issue?

**Comment by novokrest** [comment]
I found that `_converse.msg_counter` variable seems to be used for showing count of unread incoming messages in the title of browser page. But there is also `num_unread` property defined on each chatbox. At the moment, `msg_counter` and `num_unread` aren't related to each other. Because _unread_|_read_ message's status is determined by visibility of chatboxes (_open_|_minimized_|_closed_), I think, it would be better to 'bind' `msg_counter` with `num_unread` properties of chats by aggregating theirs unread message counters (pseudocode): 
`msg_counter = _.reduce(chats, (sum, chat) => sum += chat.num_unread)`

Of course, it is necessary to add updating of the `num_unread` property to other places in the code, and, I think (after looking usages of `msg_counter` and `num_unread`), this refactoring can be performed quite painlessly.

As a result, this solution will fix current bug and also introduce following changes in behavior (comparing with current): if chatboxes are minimized then **total sum** of all unread messages are **always** showed even if user has already opened page (not chatboxes!) between arriving of messages.

For example, consider following use case:

1. User opens `converse.js` page
2. User opens `chatbox1` and minimize it
3. User opens `chatbox2` and minimize it
4. User leaves `converse.js` page by opening any other browser page
5. Message is received in `chatbox1`: `converse.js`-page's title is appended by `Messages(1)`
6. Message is received in `chatbox2`: `converse.js`-page's title is appended by `Messages(2)`
7. User returns to `converse.js`-page: `Messages(2)` is removed from title
8. User leaves `converse.js`-page again
9. Another message is received in `chatbox1`: `converse.js`-page's title is appended by `Messages(3)`. And I have to pay yours attention that this step will be **differs** from current behavior because in current implementation title is appended with `Messages(1)` again (despite the fact that the number of unread messages is 3).

@jcbrand What do you think, whether it would be acceptable?

**Comment by jcbrand** [comment]
Hi @novokrest, sounds good and you're welcome to work on this.

You might notice that I did some work recently to also add a `num_unread` counter to RosterContact objects so that we can have an unread messages counter on the roster (for example when messages are received to a minimized chatbox).

I don't think that work changes anything that you wrote above, but I just wanted to make you aware of it.

**Comment by Lakshumma** [comment]
I need similar reference code, my requirement is to show the azure web chat message notification count on given icon.can anyone help here?
