### ISSUE TITLE
Typing notification if contact's name has a space

### ISSUE THREAD

**Issue by badfiles** [jcbrand/converse.js#609]
If a buddy's name has a space, his name is truncated in typing notification.

**Comment by jcbrand** [comment]
I think that's by design. Can you show a screenshot?

**Comment by badfiles** [comment]
![screenshot from 2016-03-08 15-45-40](https://cloud.githubusercontent.com/assets/1597304/13602088/70f03d40-e545-11e5-98b1-902df010eb6f.png)

**Comment by badfiles** [comment]
Additionally, `red` the messages about status are fine, only typing notifications affected.

**Comment by lixmal** [comment]
this one is the culprit:

`                fullname = (_.isEmpty(fullname) ? from: fullname).split(' ')[0];`

**converse-core.js**, line 1244

I don't know why the split is necessary, so I won't touch this.

**Comment by jcbrand** [comment]
@lixmal The idea was simply to only show the user's first name instead of the entire name (first name + surname).

However that was probably not such a good idea and it's also not consistent with other notifications as far as I know, so this can be changed.

If you make a pull request for this I'll merge it.
