### ISSUE TITLE
Problem on Ubuntu Touch/Phone - Chat Window close after 1 second

### ISSUE THREAD

**Issue by ds2k5** [jcbrand/converse.js#622]
Hello,
i made a "quick and dirty" [click Package](http://www64.zippyshare.com/v/QSWDLvt4/file.html) for Ubuntu Touch/Phone
from your "conversejs" git repo.

Thanks for the awesome app.

I modify only the index.html

Now i have a litte problem, hope you can help me.

My steps

0. install the click package on the phone ( pkcon install-local --allow-untrusted <packagename>.click )
1. start the app
2. login with my jabber accout
3. add a buddy
4. try to open the link zu the buddy - for a chat

the Chat Window is open for 1 second or so
and close. It do no keep open.
Also if i [minimize](http://postimg.org/image/4xvh2vwk1/) the "Contact"/"Main" Window

[see here: on the Phone] (http://postimg.org/image/6ab5jewdb/)

If i do this on the System with the Ubuntu SDK
i got a 2nd Window.

[see here: SDK](http://postimg.org/image/vqc9njo6l/)

webapp-container index.html

But on the phone this is not possible (i think)
beacuse no free space on the display.

**Comment by jcbrand** [comment]
Can you give the exact screen dimensions of the phone?

Converse.js automatically trims chats so that they don't overlap one another. You might have noticed if you open more chats than can appear on the screen that the oldest chats get minimized (i.e. trimmed).

I think something like that is happening here. I would actually expect the control box to be trimmed and the newly opened chat to stay open, but sometimes the trimming code does funny things.

**Comment by ds2k5** [comment]
>Can you give the exact screen dimensions of the phone?

Display: 4.5 in, IPS, 540 x 960 Pixel
It is a bq Aquaris E4.5 Ubuntu Edtion
http://www.devicespecifications.com/en/model/a12a30e4

**Comment by jcbrand** [comment]
I think it should be fixed now. Can you please check?

**Comment by ds2k5** [comment]
No it is the same problem.
i have copy alle files from a new git clone https://github.com/jcbrand/converse.js/
to the SDK Project, and build a new click package.
Deinstalled the old on the phone and installed the new one.
Here you can check if i made a mistake

**Comment by jcbrand** [comment]
> but the sounds did not work, i thought if there is a new message then there is a sound

Does it work in the SDK? Did you set `play_sounds` to `true`?

> if i minimize the contacts somtimes it is gone. so i can't open it see only a black background

There should be a small tab/toggle at the bottom right, with the text "Contacts", which you can click to open the contacts box again. Is that not visible?

I think for mobile usage, we should actually remove the ability to close the contacts box (what I call the control box) and also the ability to minimize chats.

That should solve this problem for you.

I'll have to think a bit on how to best achieve that. I think in your case, I would recommend creating a custom build without the `converse-minimize.js` component. That would remove all the minimization and trimming code, which is not needed in your case.

However, that doesn't yet go far enough, because we also need to prevent the control box from being closed and we need to not show the minimize buttons (the separation of code/components is still not totally clean there).

> and if the phone switch to "horizontal format", scroll/swipe did not work
> see here: http://postimg.org/image/xtrde40m9/ and http://postimg.org/image/cbemu7gxl/

Yeah, so it doesn't responsively resize to fit the screen in landscape mode. I think this is mostly a Sass/CSS issue. I'll have to look into it.

> if i open a "room" and invite some chat works, but if i close the "room" got also black background and nothing more.

Hmm,  so for some reason the control box got closed? The above suggestion of preventing the control box from ever getting closed should solve that.

BTW, do you have a repo for this on Github or something similar somewhere?

**Comment by ds2k5** [comment]
>Does it work in the SDK? Did you set play_sounds to true?

sorry had no chance to check this at the moment

>There should be a small tab/toggle at the bottom right, with the text "Contacts", which you can click to >open the contacts box again. Is that not visible?

somtimes yes, somtimes no

>Yeah, so it doesn't responsively resize to fit the screen in landscape mode. I think this is mostly a >Sass/CSS issue. I'll have to look into it.

thanks

**Comment by ds2k5** [comment]
If you have a Ubuntu System
and your are interested in you can install the Emulator

https://wiki.ubuntu.com/Touch/Emulator

If you what you can test it with the click Package

For me it did not work in my Virtual Maschine.

**Comment by jcbrand** [comment]
Ok, I made to improvements now.

Firstly, you'll need to make a custom build, to remove the `converse-minimize` component, because you don't want minimization/trimming on mobile.

Do this by running the following steps:
* edit `converse.js` and near the bottom of the file, remove the line `converse-minimize` (line 244).
* generate new builds by running `make dist` inside the repo.

Now you'll have custom builds in the `dist/` directory, which you can use.

On more thing, when you call `converse.initialize`, pass in the values `show_controlbox_by_default: true` and `sticky_controlbox: true`.

Then the controlbox won't be closable anymore (there won't be a close button at all). Also, there won't be minimize buttons for chats (although they'll still have close buttons).

This should improve things quite a bit for you.

I don't have more time available today to look at the landscaping issue. That'll have to wait for another time.

**Comment by ds2k5** [comment]
>    edit converse.js and near the bottom of the file, remove the line converse-minimize (line 244).
>    generate new builds by running make dist inside the repo.


thanks, but got a lot of errors


developer@touch:~/conversejs/www$ make dist
npm install
npm WARN deprecated grunt-lib-contrib@0.7.1: DEPRECATED. See readme: https://github.com/gruntjs/grunt-lib-contrib
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated graceful-fs@1.1.14: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/
> phantomjs@1.9.19 install /home/developer/conversejs/www/node_modules/phantomjs
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.19 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.19.0-56-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/developer/conversejs/www
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/developer/conversejs/www/npm-debug.log
npm ERR! not ok code 0
Makefile:104: recipe for target 'stamp-npm' failed
make: *** [stamp-npm] Error 1

**Comment by jcbrand** [comment]
> npm WARN This failure might be due to the use of legacy binary "node"

Your versions of node.js and NPM are ancient.

Please update them and then try again.

My versions:
```
jc@conversejs-11:34:~/converse.js (master)$ npm --version
2.14.12
jc@conversejs-11:34:~/converse.js (master)$ node --version
v4.3.1
```

**Comment by ds2k5** [comment]
thanks i will try

https://nodejs.org/en/download/

**Comment by jcbrand** [comment]
Please paste the log in something like pastie.org

**Comment by ds2k5** [comment]
OK, sorry
here the LINK: http://pastie.org/private/zzps2hjf64huvqxelwo8a

**Comment by jcbrand** [comment]
Looks like the bower dependencies are installed in a `bower_components` directory, instead of in `components`. That's strange. It must mean that the `.bowerrc` file in your checkout of the repo is being overridden somehow.

First, check whether you actually have the `.bowerrc` file.
Second, can you tell me what version of bower you're using?
```
jc@conversejs-07:39:~/converse.js (mind)$ ./node_modules/.bin/bower --version
1.7.7
```

According to the bower docs, the `.bowerrc` will only be overridden by CLI arguments via ``--config`` or environment variables.

I guess we can rule out CLI arguments, since you are using the Makefile. That leaves environment variables. I'm not sure which those would be, because they don't mention them.

Do you perhaps have an idea why this might be?

**Comment by ds2k5** [comment]
developer@touch:~/conversejs/www/node_modules/.bin$ ./bower --version
1.7.7

File: .bowerrc i did not find

**Comment by jcbrand** [comment]
`.bowerrc` should be in `~/conversejs/www/`.

If it's not there, then that's the problem. What does `git status` in `~/conversejs/www/` say?

**Comment by ds2k5** [comment]
>What does git status in ~/conversejs/www/ say?

fatal: Not a git repository (or any of the parent directories): .git

**Comment by jcbrand** [comment]
I've now created a new build specifically for mobile. You'll find it in `builds/converse-mobile.js`.

I don't include minimized files in the repo, because they bloat the repo. But perhaps you know how to minimize a JS file? It would of course be much better to use a minimized file.

I still have to find a satisfactory solution for that.

**Comment by edwh** [comment]
I use JSMin.php for JS minimisation.

I may be misreading this thread, but are you heading towards having a separate deliverable for mobile, with the client having to decide which one to include?

**Comment by jcbrand** [comment]
> I may be misreading this thread, but are you heading towards having a separate deliverable for mobile, with the client having to decide which one to include?

Kind of. It depends on your needs. For example, on https://conversejs.org, if the site is loaded on mobile, you still want to be able to minimize chats, but you don't want trimming of chats and you don't need resizing of chats.

When using converse.js as an app (like in Ubuntu or with Cordova), you don't want either.

In either case, it makes sense to make a separate build for mobile, and to have the website serve the right build depending on the device accessing it.

Generally I think people need to figure out for themselves what their usecases are and ideally create their own builds based on that. I know making builds is hard for some people. I'm trying to make that easier, and I'm also thinking of creating a graphical tool to make it even easier.

**Comment by edwh** [comment]
Well, it's your code.  But I really wouldn't go down that route.  I think there's an argument that most things you might need to make it work well on mobile are either:

- Things you can handle responsively, or

- Things which should be features under user control because you might want to modify how it behaves in some integration cases

A good example is my other suggestion of the ability to open chats minimised.  You could argue that this is a mobile thing, since there's limited screen real estate. But in some cases, the chat might be a secondary part of the website and you'd not want to flood the screen, just set up some minimised chat windows so that people see any notifications.

I think if you go down the route of hardcoding what is and what isn't a mobile feature,. then you'll find (or the users of your very kindly provided code will find) that your choices don't match how they want to use it.

**Comment by jcbrand** [comment]
> I think if you go down the route of hardcoding what is and what isn't a mobile feature

Nothing is hardcoded and it's possible to make custom builds which include exactly the components and features you want.

**Comment by edwh** [comment]
There's a big difference in ease of use between including a library source file that you can just download and selecting what you want to use based on features in the initialize call, vs setting up a build environment in some system you may never have used before.  If I'd read that I would have to generate my own build I'd probably not have started to try Converse at all - the barrier to entry would be too high, and I'd have kept looking for something else.  And surely you don't want to be spending your time telling people how to get their build systems working. 

However, like I say, it's your code, and you undoubtedly have more experience with how people use Converse than I do, so I'll shut up now...

**Comment by jcbrand** [comment]
>  If I'd read that I would have to generate my own build for mobile

You keep on making unwarranted assumptions. I never said that you *have* to generate your own build, I simply said that it's possible. Just like I never said that I'm *hardcoding* anything for mobile.

You can use the standard build if you want to, and by and large it should work in most situations. That's the ideal I'm striving for. However, if you are a power user or integrator, then you are also empowered to modify, expand or customize converse.js to meet your particular needs.

I get lots of requests and questions from people who want to disable certain features or functionalities. If you don't need a certain piece of functionality, it makes sense to remove that code entirely (if possible, and which is what I'm now making possible), instead of shipping "dead code" which provides functionality which you don't need and which could be exploited in unforeseen ways. It also makes your webpages lighter and therefore quicker to serve (especially on mobile, where data is expensive and connections are unstable).

FOSS is first and foremost (to me at least) about empowering the user to use and modify the software for their own needs.

That said, I'll continue to try and make converse.js as easy to use as possible, while also making it customizable and extensible. With that in mind, it helps if people give me examples or suggestions on how things could be made better or easier for them, since I don't know all the pain-points myself. So thanks for sharing your insights, and if you have concrete suggestions for enhancements, you can create tickets for those.

I hope that allays some of your fears :)

I'll close this ticket now.
