### ISSUE TITLE
test with Samsung Z3

### ISSUE THREAD

**Issue by swift11** [jcbrand/converse.js#639]
Thanks, the new release is much better on my mobile phone (Samsung Z3)
There is still 1 problem though: the user has to scroll down to see the message input field
Screenshots: https://www.dropbox.com/sh/vm017xwe2yx87rb/AAClaiLlXCUXvV6I3Fk8FLXxa?dl=0

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/33912604-test-with-samsung-z3?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

**Comment by jcbrand** [comment]
Are you using the https://conversejs.org or are you using your own hosted version? If you are hosting it yourself, make sure you're using [converse-mobile.js](https://github.com/jcbrand/converse.js/blob/master/dist/converse-mobile.js) on mobile devices, and not converse.js (of course, also minimize the files before).

I still want to update the conversejs.org website to serve the mobile JS for mobile devices and the normal JS otherwise, but I haven't gotten around to that yet, so it only serves the "normal" JS for now.

**Comment by swift11** [comment]
yep, I'm using conversejs.org :)

**Comment by jcbrand** [comment]
m.conversejs.org now servers the mobile build of converse.js
