### ISSUE TITLE
1.0.2 Archived message Problem (Ignoring incoming message sent from this client's JID)

### ISSUE THREAD

**Issue by julian-d** [jcbrand/converse.js#650]
I had a problem with loading archived messages. I always got

 "onMessage: Ignoring incoming message sent from this client's JID"

I changed on  line 1271:
`} else if (from_jid === converse.connection.jid) {`
to 
`} else if (from_bare_jid === converse.connection.jid) {`

and now everything works as expected.

**Comment by jcbrand** [comment]
It's not clear to me under what circumstances that will be true with regards to MAM. Do you perhaps keep the same resource across page reloads?

I don't think the change you made makes any sense. It'll never be true since `converse.connection.jid` is always the full JID.

I've removed that check for now, and will see if it has any adverse effects.

**Comment by julian-d** [comment]
Fixed thanks!
