### ISSUE TITLE
converse sudently stop working!

### ISSUE THREAD

**Issue by mckaygerhard** [jcbrand/converse.js#664]
i'm try to fixed the very abandoned converse.js plugin or roundcube.. and use the lasted in that moment, i think 0.9 or something but yesterday sudently stop working

i noted that try to render and due i use same identification for resource in prebind, but seems i dont know if this domain "http://jabber.org/protocol/httpbind" have someting related due now are not found! 

i used the php xmpp prebind library from candy chat with very smal modifications, works perfectly until yesterday, please some body helpme!

**Comment by mckaygerhard** [comment]
when i used diferen resource for jid, the chat works perfectly making resource identification = jid / random()

but the rare behavior its until yesterday every thing are working and now not!

**Comment by jcbrand** [comment]
Doesn't sound like there's anything to do here regarding converse.js.

**Comment by mckaygerhard** [comment]
but i can login using pidgin and spark, but not with converse!

**Comment by jcbrand** [comment]
Those clients don't use BOSH and you don't specify your resource when you're using them. You mentioned that the issue went away when you stopped using the same resource.

The issue is probably in the way you're using BOSH.

Do you have `keepalive` set to `true`? Using that together with the `prebind_url` option, you won't need to create an authenticated BOSH session for each page load. That might help.
