### ISSUE TITLE
Can't change langage converse.js

### ISSUE THREAD

**Issue by Catskan** [jcbrand/converse.js#669]
Hi, 

I setting up a converse.js module on my website with the source but I can't change the locale on this.

In my folder `./locales/` I have `fr/LC_MESSAGES/converse.json and converse.po` but when I change to `i18n: locales.fr` in my html file, my chat keep the original locale.

**Comment by jcbrand** [comment]
It doesn't work that way. You can't access `locales.fr` just because you have a `locales/fr/` directory structure. The `locales` variable refers to a global object, not to a directory, and the locales in this object need to specifically be set, for example here: https://github.com/jcbrand/converse.js/blob/master/src/locales.js#L30

Whether the locales are available depends on how you load converse.js, for example whether you use require.js or whether you use a built file in the `dist` directory.

**Comment by jcbrand** [comment]
I found a bug in the current unreleased version of converse.js which might have contributed to your problem. We're you using the master branch or a released version of converse.js?
