### ISSUE TITLE
chat status not in real time

### ISSUE THREAD

**Issue by PegasusGo** [jcbrand/converse.js#685]
Hello,

I have a bug status of friends chat, I have successfully installed conversejs with ejabberd and mysql but the chat didnt update when a friend disconnect from my website. But when I close my website window on firefox and re-open it, the chat has updated well

How can I fix it?

Thanks

**Comment by jcbrand** [comment]
Please be more specific. What do you mean "the chat didnt update"?

**Comment by PegasusGo** [comment]
I need to close and re-open my website to see chat updated

**Comment by jcbrand** [comment]
Do you mean the user doesn't get shown as offline immediately once they've closed their browser?

That's normal and there's not much that can be done about that. We can't set the user's status to offline before they close the browser because it will also affect page reloads.

After a while the XMPP server will recognise that the other user is offline and then update the presence.
