### ISSUE TITLE
logout url

### ISSUE THREAD

**Issue by camaran** [jcbrand/converse.js#714]
Add a custom variable for logout_url to specify a url to redirect the user when logout

**Comment by jcbrand** [comment]
I've added a `logout` event, that you can listen to and then change the URL:
```
converse.listen.on('logout', function (ev) {
    window.location.href = "www.example.org"; 
});

**Comment by jcbrand** [comment]
You'll have to wait for the next release however, or make a build of the current release yourself.

**Comment by camaran** [comment]
for example i must wirte this:
`<script>
require(['converse'], function (converse) {
    converse.initialize({
        bosh_service_url: 'https://bind.conversejs.org', // Please use this connection manager only for testing purposes
        i18n: locales.en, // Refer to ./locale/locales.js to see which locales are supported
        show_controlbox_by_default: true,
        roster_groups: true
    });
});
converse.listen.on('logout', function (ev) {
    window.location.href = "www.example.org"; 
});
</script>`

**Comment by jcbrand** [comment]
You want to `converse.listen` part to be inside the `require` callback, otherwise it could execute before `converse.js` has been loaded.

Also, it's best to put the code in a plugin. To improve security, I'm soon going to update converse.js to allow only plugins to listen to events. And then I'm going to allow people to whitelist plugins.

So the code should rather look like this:

<script>
require(['converse'], function (converse) {

    converse.plugins.add('chatme', {
        initialize: function () {
            converse.listen.on('logout', function (ev) {
                window.location.href = "www.example.org"; 
            });
        }
   });

    converse.initialize({
        bosh_service_url: 'https://bind.conversejs.org',
        i18n: locales.en, // Refer to ./locale/locales.js to see which locales are supported
        show_controlbox_by_default: true,
        roster_groups: true
    });
});
</script>

**Comment by camaran** [comment]
thank you
