### ISSUE TITLE
Hello world inline minimal plugin

### ISSUE THREAD

**Issue by umpirsky** [jcbrand/converse.js#761]
I am trying to setup hello world plugin which just overrides `renderMessage`, but looks like it's never registered.

I see similar question is asked here https://github.com/jcbrand/converse.js/issues/654, but I have a concrete jsfiddle which we can iterate over to make a working example which can be useful resource for everybody.

https://jsfiddle.net/umpirsky/4drfaok0/2/

/cc @jcbrand

**Comment by jcbrand** [comment]
`renderMessage` is a method on `ChatBoxView`.

Currently you're trying to override it as if it's a global function inside converse.

Look how the "converse-mam" plugin overrides the `render` method on the `ChatBoxView`. That's how you're override structure should look as well. In other words, you pass in `ChatBoxView` as a key of the overrides map, and then its value is another map with `renderMessage` as key and your function as value. Additionally, you need to call the original method, otherwise the message won't get rendered: `var result = this.__super__.renderMessage.apply(this, arguments);`

**Comment by umpirsky** [comment]
@jcbrand Thanks for quick answer, really appreciate it! :+1: 

I updated implementation to:

```js
(function (root, factory) {
    define("umpirsky-plugin", ['converse'], factory);
}(this, function (converse, converse_api) {
    "use strict";

    converse_api.plugins.add('umpirsky-plugin', {
        overrides: {
            ChatBoxView: {
                renderMessage: function () {
                    console.log('render');
                    return this.__super__.renderMessage.apply(this, arguments);
                },
                fetchArchivedMessages: function () {
                    console.log('fetchArchivedMessages');
                    return this.__super__.fetchArchivedMessages.apply(this, arguments);
                },
            },
        },
    });
}));
```

But still cannot get this methods called.

Thanks again.

**Comment by jcbrand** [comment]
Change this line `}(this, function (converse, converse_api) {` to this `}(this, function (converse_api) {`, since  you have only one AMD/require.js dependency, `converse`, which is the API.

That's all I can see that's still not correct.

**Comment by umpirsky** [comment]
Thanks @jcbrand!

Unfortunatelly this didn't make it work for me.

But maybe it works and I'm not understanding `renderMessage()` correctly. I want `console.log('render');` to be called each time new message is rendered inside chat window, be it me sending or receiving it. Am I on the right track?

Here is updated https://jsfiddle.net/umpirsky/4drfaok0/5/

**Comment by jcbrand** [comment]
@umpirsky I updated the plugin to work.

See here: https://jsfiddle.net/4drfaok0/15/

`renderMessage` is a method on the `ChatBoxView` Backbone.View object. So you needed to change the `overrides` object to reflect that.

Also, `plugins.add` must be called **before** `converse.initialize` is called, otherwise it won't get registered.

**Comment by jcbrand** [comment]
In case the fiddle goes away for some reason, here's the code:

```javascript
converse.plugins.add('myplugin', {
     initialize: function () {
         alert('myplugin initialize called!');
     },
     overrides: {
         ChatBoxView: {
             renderMessage: function (attrs) {
                 alert('render message.');
                 return this.__super__.renderMessage.apply(
                     this, arguments);
             }
         }
     }
});

converse.initialize({
    bosh_service_url: 'https://conversejs.org/http-bind/',
    show_controlbox_by_default: true,
    whitelisted_plugins: ['myplugin']
});
```

**Comment by umpirsky** [comment]
That worked, thanks @jcbrand!
