### ISSUE TITLE
CDN 404 for v2.0.4

### ISSUE THREAD

**Issue by umpirsky** [jcbrand/converse.js#794]
I have been using https://cdn.conversejs.org/2.0.4/components/typeahead.js/index.js for some time, and it started to 404.

Any idea why? Are urls updated?

Thanks.

**Comment by jcbrand** [comment]
I removed the dependencies from the CDN and kept just the build files.

Why don't you just use the builds in the `./dist/` directory?
E.g. https://cdn.conversejs.org/2.0.4/dist/converse.min.js

v2.0.4 contains known security holes, so you should update to v2.0.6

**Comment by umpirsky** [comment]
@jcbrand Thanks for the quick answer.

Idon't use entire build because it colides with my version of jQuery and I don't use AMD...

**Comment by jcbrand** [comment]
@umpirsky What version of jQuery do you use? You could use the entire converse.js build and then use its version of jQuery, which you can set on the window object, e.g. `window.$ = converse.env.jQuery`

Also, you don't need AMD to load the build.
 
Unfortunately the build pollutes the global namespace with `require` and `define`, but I fixed that in master and in the upcoming 3.0.0 release this won't be happening anymore.

The reason I removed the dependencies was because I didn't want someone to use something like http://cdn.conversejs.org/2.0.4/index.html which would be the full application with known security issues. In other words, people could be directed to chat there and then attacked.

Therefore I only want the latest version to be usable as a hosted application.

**Comment by umpirsky** [comment]
@jcbrand I use 1.11.0. I want my old code to keep using that version, and it appears that converse is also compatible with it. 

Will `window.$ = converse.env.jQuery` allow me to use my own version of jQuery and let converse use it's own?

Thanks!

**Comment by jcbrand** [comment]
No, `window.$ = converse.env.jQuery` is to let the whole site use the jQuery from converse.

However, if you want to let converse use its own, you can simply include the build. It will use its own jQuery and it will not affect or influence the the older jQuery 1.11.0 you're using elsewhere because it doesn't use or change the global `$` or `jQuery` variables.

**Comment by umpirsky** [comment]
@jcbrand OK, will try that, sound good, but I remember it caused some issues in my case, will double check, thanks!

**Comment by umpirsky** [comment]
@jcbrand Here is why I cannot use entire build.

I use bootstrap modal, and getting `TypeError: formulaModal.modal is not a function` error when trying to use bootstrap modal.

On http://stackoverflow.com/questions/25757968/bootstrap-modal-is-not-a-function I found:

> This warning may also be shown if jQuery is declared more than once in your code. The second jQuery declaration prevents bootstrap.js from working correctly

So, I really need only one jQuery included.
