### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Jibec** [jcbrand/converse.js#843]
hi,

I think something changed in converse.js, because my applet didn't work anymore (I can't tell when it started)

I had this:
`<script>
require(['converse'], function (converse) {
    converse.initialize({
        blabla
    });
});
</script>`

To make it works again:
`<script>
    converse.initialize({
        blabla
    });
</script>`

I'm quite surprise this can happen, should we start using lastest javscript file and import the right version number? what do you suggest?

thanks for your help

**Comment by jcbrand** [comment]
This change happened in 3.0.0 and is one of the reasons why a major version bump was made from 2.x.x. to 3.x.x (with [semantic versioning](http://semver.org/) major version bumps imply that backwards incompatible changes were made and that things might break).

The reason `require` is no longer available is because the way converse.js gets bundled has changed to conform to the way the require.js docs say it should be done.

As a result the `require` function is no longer available in the global namespace, which is actually a good thing because it avoids clashes with other libraries and turns out it wasn't necessary in any case.
