### ISSUE TITLE
update user groups

### ISSUE THREAD

**Issue by proton5000** [jcbrand/converse.js#893]
when i add user to group in openfire server, convers not sync user groups, i need only re-login user to update user groups.
how can i update user groups in converse without relogin user???

please help me to solve this problem :'(

**Comment by jcbrand** [comment]
Turn on debug in converse.js, then check in the browser console whether any XMPP stanzas are received from OpenFire when you update the user groups.

If OpenFire sends an XMPP stanza to converse.js telling it to update the roster, then we can do something about it. Otherwise, if OpenFire doesn't send out such a stanza, then there's nothing that converse.js can do about it.

**Comment by proton5000** [comment]
Tell me which listener should I use to listen to the update of user groups?

**Comment by jcbrand** [comment]
You can listen for the ``rosterPush`` event.

https://github.com/jcbrand/converse.js/blob/d527f693c22b3eded8c638004f85901eac775b7f/src/converse-core.js#L1154

**Comment by proton5000** [comment]
listen for the `rosterpPush` is help me, thanks
But the avatars of users will be updated in a very long period of time, how can this process be accelerated ???

**Comment by jcbrand** [comment]
You'll have to study the code and write a plugin to override the way avatars get updated.
