### ISSUE TITLE
Change label from "Jabber ID" to "XMPP/Jabber ID" or "XMPP ID"?

### ISSUE THREAD

**Issue by marclaporte** [jcbrand/converse.js#896]
I see:
"All other room occupants can see your Jabber ID"
"Only moderators can see your Jabber ID"

In other places, I see XMPP/Jabber ID

What is our policy on this?

Thanks!

**Comment by jcbrand** [comment]
The only place I can currently think of where `XMPP/Jabber ID` is being used is the login form.

Otherwise I think we generally use `Jabber ID` or `JID` for short.

Personally, I'd be happy to move away from the `Jabber` name altogether and just use XMPP, but it's called a `Jabber ID` since always, so it doesn't make sense IMO to change that.
