### ISSUE TITLE
How to change chat messages history source?

### ISSUE THREAD

**Issue by jim10** [jcbrand/converse.js#915]
I am using Converse.js with Openfire Server to implement a chat. Chatting works fine. What I want to do is include in chat history between users some messages that I'm getting from calling a seperate API.

I couldn't manage to find in converse's code where the loading of older messages is happening to change it. Could anyone point me in the right direction?

**Comment by jcbrand** [comment]
I see you also asked this question in StackOverflow, which is a better place to ask questions such as this one. This issue tracker is for bug reports and feature requests, not really for asking help in customizing or extending converse.js.

However, the SO question you posted has been put on hold because you didn't word it in a clear way. I've edited your question, perhaps my edit gets approved and the question taken off hold.
Then I'll add an answer there.

To answer shortly, the code that loads older messages is in [src/converse-mam.js](https://github.com/jcbrand/converse.js/issues/915).
