### ISSUE TITLE
Dont want user to create Room but allow user to access existing room

### ISSUE THREAD

**Issue by rheman** [jcbrand/converse.js#944]
Hi everyone I have a problem `muc_instant_rooms`
I also want to know if it is possible to set a room is such a way that user can only acces room and cannot create room ? I have set  `muc_instant_rooms` but user can still create rooms.

My environment looks as followed:

ejabberd 16.09 with mod_mam support (mysql based)
conversejs lastest release (v 3.0.2) // I cannot use conversejs lastest release because my server does not support mam:2 for message_archiving

Best regard

**Comment by jcbrand** [comment]
You could maybe use the [auto_list_rooms](https://conversejs.org/docs/html/configuration.html#auto-list-rooms) setting and then hide the "join room" form, either via CSS or in a custom plugin.

Other than that, I don't think there is currently a way in converse.js to restrict users from creating new rooms because creating a room and entering an existing room happens in the same way.

**Comment by rheman** [comment]
Thanks a lot
