### ISSUE TITLE
Filter input flashes upon login

### ISSUE THREAD

**Issue by kvinayak1991** [jcbrand/converse.js#949]
after login search bar get appeared for 1 second after that it will get disappeared i used  recent converse js

**Comment by jcbrand** [comment]
It's not for searching, but for filtering of roster contacts. The filter input will only show if you have enough roster contacts to cause scrolling (i.e. there are more contacts that can be shown in the visible area). Otherwise it gets hidden.

I think the "flashing" of the filter input after login is confusing however, so I've made a note to look into fixing that.
