### ISSUE TITLE
When's the right time to join a MUC channel in a plugin?

### ISSUE THREAD

**Issue by iagox86** [jcbrand/converse.js#954]
In all the examples, it says:

    converse.plugins.add('myplugin', {
        initialize: function () {
    
            this._converse.api.rooms.open('group@muc.example.com')
    
        }
    });

But I get an error when I do that. If I put `setTimeout(myjoiner, 5000);` there instead, it works, so presumably the problem is that the connection isn't fully initialized yet. I was looking at different events, and the most logical one seemed to be `onConnected`, but that has the same error.

If it helps, this is the error:

    converse.js:47660  2017-11-16T07:31:08-08:00 FATAL: Error: A "url" property or function must be specified
        at urlError (http://localhost:4200/assets/vendor.js:113833:11)
        at child.url (http://localhost:4200/assets/vendor.js:112620:9)
        at Function.result (http://localhost:4200/assets/vendor.js:84085:44)
        at child.Backbone.sync (http://localhost:4200/assets/vendor.js:113328:22)
        at child.Backbone.sync (http://localhost:4200/assets/vendor.js:114124:40)
        at child.sync (http://localhost:4200/assets/vendor.js:112363:28)
        at child.save (http://localhost:4200/assets/vendor.js:112574:22)
        at child.initialize (http://localhost:4200/assets/vendor.js:115594:22)
        at child.initialize (http://localhost:4200/assets/vendor.js:125203:51)
        at child.wrappedOverride (http://localhost:4200/assets/vendor.js:111723:26)

I googled the error, and found some issues here, but none of them seem to be right.

Any advice?

Thanks!

**Comment by iagox86** [comment]
`roomsAutoJoined` seems to work out of the box, but I'm not sure if that is the "right" place?

**Comment by jcbrand** [comment]
`roomsAutoJoined` is fine if you're able to configure how `converse.initialized` is called. However, in some cases you might want to open a room based on certain logic which only executes after `converse.initialized` has been called, in which case you'll need to call the API method.

The API documentation is still very much lacking when it comes to asynchronicity and how to wait until it's the right time to do something. Sorry about that. Generally as these issues come in and the inadequacies of the documentation becomes clear I update the docs, but the changes only become visible with the next release.

Perhaps it's not a documentation issue however, I've been thinking of updating the API to make it Promise-based. So that you can basically call anything at any time (as long as there is already a working XMPP-connection) and that "waiting for the right time" will be done automatically by converse.js.

In the meantime, you can read this answer on StackOverflow for an general explanation of timing issues: https://stackoverflow.com/questions/47034244/converse-opening-a-chat-from-api

For specifically MUC, you could use `_converse.api.waitUntil('roomsAutoJoined')` as hook to make sure everything is set up properly before opening a chat room.

**Comment by iagox86** [comment]
Cool, thanks!

I need to change rooms at random times (it's for a chat system as part of a game). I ended up just using roomsAutoJoined, then using setInterval() to poll for room changes and update rooms accordingly. It's kinda ugly, it'd be nice to have access via the API, but it works okay.
