### ISSUE TITLE
How to set a particular language as default in converse.js

### ISSUE THREAD

**Issue by k0fi** [jcbrand/converse.js#992]
Hello,
I want to set converse.js chat with a single language locale, say `fr`, no matter what is the user's browser language:

The [docs][1] say:

     Default: Auto-detection of the User/Browser language
    If no locale is matching available locales, the default is en. Specify the locale/language. The language must be in the locales object. Refer to ./locale/locales.js to see which locales are supported.

Apart from the fact that I could not find  `./locale/locales.js` file, what I did was this:

In `converse.js` file, I changed `detectLocale` function to:

    function detectLocale (library_check) {
        return  'fr';
    } 

And restricted locales to:

     locales: ['fr'],

In order to eliminate detecting locale from browser
 

Also I replaced all instances of `'en'` with `'fr'` in `converse.js` file. 

And of course I cleared browser cache. 

But the chat language is still `en` (on my 'en' broswer).

How can I resolve this?

Thanks

  [1]: https://conversejs.org/docs/html/configuration.html?highlight=language

**Comment by jcbrand** [comment]
How it should work is that when you call `converse.initialize` you pass in `i81n: 'fr'`.
Like here: https://github.com/jcbrand/converse.js/blob/master/dev.html#L57

There is a bug in the latest release where this doesn't work properly. This has been fixed long ago but the fix is being held up by the next release.

I'll make the next release before the end of this week.

**Comment by jcbrand** [comment]
Version 3.3.0 has been released, so should be working now.
